name: XPBank
version: 1.5.2
main: fr.yamakaky.pluginxpbank.Main
author: Yamakaky
permissions:
  xpbank.use:
    description: give the permission to use an xp bank sign
    default: true
  xpbank.place:
    description: give the permission to create an xp bank sign
    default: op